# Generated by Django 6.0.7 on 2026-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_contact_phone_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid_pending_confirmation', 'Payment Claimed — Awaiting Confirmation'), ('confirmed', 'Payment Confirmed')], default='unpaid', max_length=30),
        ),
    ]
