# Generated by Django 6.0.7 on 2026-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_contactmessage_responded_at_contactmessage_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
